elasticsearch:
  host: 192.168.23.124
  port: 9200
# datasource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/person_study?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: elasticsearch
server:
  port: 8081